### PR TITLE
Revert "Use try with resources for all closeables."

### PR DESCRIPTION
**Pull request by tidyjava**
Reverts tidyjava/blogging-platform#11

### CODE REVIEW

**Comment by codingtim** [comment]
It didn't work?

**Comment by tidyjava** [comment]
I'm wondering about try-with-resources in `GitPostReader` - I'm closing the `Git` (and therefore underlying `Repository`) when application is closed, see `closeRepository`. I **don't know** if we need extra try-with-resources when using them.

**Comment by tidyjava** [comment]
Doesn't the code below return a closed resource (while I still want to use it)?

```
try (autoclosable = getAutoclosable()) {
    return autoclosable;
}
```

**Comment by codingtim** [comment]
I think you are correct. I was too hasty to close that one.

**Comment by tidyjava** [comment]
Cool, can you make a PR with just `MarkdownPostFactory`? I don't want to take away the fame from having a contributor :smiley:

**Comment by codingtim** [comment]
Had some work setting up the upstream tracking on my repo. But pull request is created.

**Pull request merged**
